//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emi.Portal.Movil.Logic.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppConfigurations {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppConfigurations() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Emi.Portal.Movil.Logic.Resources.AppConfigurations", typeof(AppConfigurations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AgendaType {
            get {
                return ResourceManager.GetString("AgendaType", resourceCulture);
            }
        }
        
        public static string ApplicationJson {
            get {
                return ResourceManager.GetString("ApplicationJson", resourceCulture);
            }
        }
        
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        public static string CellPhone {
            get {
                return ResourceManager.GetString("CellPhone", resourceCulture);
            }
        }
        
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        public static string RegexName {
            get {
                return ResourceManager.GetString("RegexName", resourceCulture);
            }
        }
        
        public static string ChannelKey {
            get {
                return ResourceManager.GetString("ChannelKey", resourceCulture);
            }
        }
        
        public static string ClinicCode {
            get {
                return ResourceManager.GetString("ClinicCode", resourceCulture);
            }
        }
        
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        public static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        public static string EnvironmentString {
            get {
                return ResourceManager.GetString("EnvironmentString", resourceCulture);
            }
        }
        
        public static string FamilyController {
            get {
                return ResourceManager.GetString("FamilyController", resourceCulture);
            }
        }
        
        public static string GetMembers {
            get {
                return ResourceManager.GetString("GetMembers", resourceCulture);
            }
        }
        
        public static string GooglePlayWaze {
            get {
                return ResourceManager.GetString("GooglePlayWaze", resourceCulture);
            }
        }
        
        public static string GrantType {
            get {
                return ResourceManager.GetString("GrantType", resourceCulture);
            }
        }
        
        public static string IconChat {
            get {
                return ResourceManager.GetString("IconChat", resourceCulture);
            }
        }
        
        public static string IconCheck {
            get {
                return ResourceManager.GetString("IconCheck", resourceCulture);
            }
        }
        
        public static string IconGps {
            get {
                return ResourceManager.GetString("IconGps", resourceCulture);
            }
        }
        
        public static string IconLocation {
            get {
                return ResourceManager.GetString("IconLocation", resourceCulture);
            }
        }
        
        public static string IconNavigation {
            get {
                return ResourceManager.GetString("IconNavigation", resourceCulture);
            }
        }
        
        public static string IconOk {
            get {
                return ResourceManager.GetString("IconOk", resourceCulture);
            }
        }
        
        public static string IconUser {
            get {
                return ResourceManager.GetString("IconUser", resourceCulture);
            }
        }
        
        public static string IdDocument {
            get {
                return ResourceManager.GetString("IdDocument", resourceCulture);
            }
        }
        
        public static string IdReference {
            get {
                return ResourceManager.GetString("IdReference", resourceCulture);
            }
        }
        
        public static string LastNameOne {
            get {
                return ResourceManager.GetString("LastNameOne", resourceCulture);
            }
        }
        
        public static string LastNameTwo {
            get {
                return ResourceManager.GetString("LastNameTwo", resourceCulture);
            }
        }
        
        public static string LocalCode {
            get {
                return ResourceManager.GetString("LocalCode", resourceCulture);
            }
        }
        
        public static string MedicalCenterLine {
            get {
                return ResourceManager.GetString("MedicalCenterLine", resourceCulture);
            }
        }
        
        public static string NameOne {
            get {
                return ResourceManager.GetString("NameOne", resourceCulture);
            }
        }
        
        public static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        public static string NameTwo {
            get {
                return ResourceManager.GetString("NameTwo", resourceCulture);
            }
        }
        
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        public static string OcpApimSubscriptionKey {
            get {
                return ResourceManager.GetString("OcpApimSubscriptionKey", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        public static string PrimaryButtonColor {
            get {
                return ResourceManager.GetString("PrimaryButtonColor", resourceCulture);
            }
        }
        
        public static string RDACode {
            get {
                return ResourceManager.GetString("RDACode", resourceCulture);
            }
        }
        
        public static string RegexCellPhone {
            get {
                return ResourceManager.GetString("RegexCellPhone", resourceCulture);
            }
        }
        
        public static string RegexEmail {
            get {
                return ResourceManager.GetString("RegexEmail", resourceCulture);
            }
        }
        
        public static string RegexPhone {
            get {
                return ResourceManager.GetString("RegexPhone", resourceCulture);
            }
        }
        
        public static string RemoveMember {
            get {
                return ResourceManager.GetString("RemoveMember", resourceCulture);
            }
        }
        
        public static string SecundaryButtonColor {
            get {
                return ResourceManager.GetString("SecundaryButtonColor", resourceCulture);
            }
        }
        
        public static string ServiceType {
            get {
                return ResourceManager.GetString("ServiceType", resourceCulture);
            }
        }
        
        public static string SpecialityCode {
            get {
                return ResourceManager.GetString("SpecialityCode", resourceCulture);
            }
        }
        
        public static string UnauthorizedUser {
            get {
                return ResourceManager.GetString("UnauthorizedUser", resourceCulture);
            }
        }
        
        public static string UnauthorizedUserTitle {
            get {
                return ResourceManager.GetString("UnauthorizedUserTitle", resourceCulture);
            }
        }
        
        public static string SubscriptionkeyString {
            get {
                return ResourceManager.GetString("SubscriptionkeyString", resourceCulture);
            }
        }
        
        public static string Surnames {
            get {
                return ResourceManager.GetString("Surnames", resourceCulture);
            }
        }
        
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        public static string TypeDocument {
            get {
                return ResourceManager.GetString("TypeDocument", resourceCulture);
            }
        }
        
        public static string UpdateEmail {
            get {
                return ResourceManager.GetString("UpdateEmail", resourceCulture);
            }
        }
        
        public static string UpdateMember {
            get {
                return ResourceManager.GetString("UpdateMember", resourceCulture);
            }
        }
        
        public static string UrlBaseMiddleware {
            get {
                return ResourceManager.GetString("UrlBaseMiddleware", resourceCulture);
            }
        }
        
        public static string Subscriptionkey {
            get {
                return ResourceManager.GetString("Subscriptionkey", resourceCulture);
            }
        }
        
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        public static string GetEventAreas {
            get {
                return ResourceManager.GetString("GetEventAreas", resourceCulture);
            }
        }
        
        public static string WazeNavigationUrl {
            get {
                return ResourceManager.GetString("WazeNavigationUrl", resourceCulture);
            }
        }
        
        public static string YearMonthDay {
            get {
                return ResourceManager.GetString("YearMonthDay", resourceCulture);
            }
        }
        
        public static string SearchMember {
            get {
                return ResourceManager.GetString("SearchMember", resourceCulture);
            }
        }
        
        public static string GetRefundType {
            get {
                return ResourceManager.GetString("GetRefundType", resourceCulture);
            }
        }
        
        public static string FileAction {
            get {
                return ResourceManager.GetString("FileAction", resourceCulture);
            }
        }
        
        public static string CancelCoordination {
            get {
                return ResourceManager.GetString("CancelCoordination", resourceCulture);
            }
        }
        
        public static string ConfirmCoordination {
            get {
                return ResourceManager.GetString("ConfirmCoordination", resourceCulture);
            }
        }
        
        public static string CoordinationsController {
            get {
                return ResourceManager.GetString("CoordinationsController", resourceCulture);
            }
        }
        
        public static string PendingCoordinations {
            get {
                return ResourceManager.GetString("PendingCoordinations", resourceCulture);
            }
        }
        
        public static string RegistrationController {
            get {
                return ResourceManager.GetString("RegistrationController", resourceCulture);
            }
        }
        
        public static string VerifyUpdateEmailCode {
            get {
                return ResourceManager.GetString("VerifyUpdateEmailCode", resourceCulture);
            }
        }
        
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        public static string LoginController {
            get {
                return ResourceManager.GetString("LoginController", resourceCulture);
            }
        }
        
        public static string GetClinics {
            get {
                return ResourceManager.GetString("GetClinics", resourceCulture);
            }
        }
        
        public static string MiddlewareController {
            get {
                return ResourceManager.GetString("MiddlewareController", resourceCulture);
            }
        }
        
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        public static string SendVerificationCode {
            get {
                return ResourceManager.GetString("SendVerificationCode", resourceCulture);
            }
        }
        
        public static string PreRegister {
            get {
                return ResourceManager.GetString("PreRegister", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string GetDocumentTypes {
            get {
                return ResourceManager.GetString("GetDocumentTypes", resourceCulture);
            }
        }
        
        public static string MedicalCenterSchedules {
            get {
                return ResourceManager.GetString("MedicalCenterSchedules", resourceCulture);
            }
        }
        
        public static string DataListsController {
            get {
                return ResourceManager.GetString("DataListsController", resourceCulture);
            }
        }
        
        public static string GetMedicalSpecialites {
            get {
                return ResourceManager.GetString("GetMedicalSpecialites", resourceCulture);
            }
        }
        
        public static string GetServiceTypes {
            get {
                return ResourceManager.GetString("GetServiceTypes", resourceCulture);
            }
        }
        
        public static string AffiliateController {
            get {
                return ResourceManager.GetString("AffiliateController", resourceCulture);
            }
        }
        
        public static string GetBeneficiaries {
            get {
                return ResourceManager.GetString("GetBeneficiaries", resourceCulture);
            }
        }
        
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        public static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        public static string GetAffiliate {
            get {
                return ResourceManager.GetString("GetAffiliate", resourceCulture);
            }
        }
        
        public static string UpdateAffiliate {
            get {
                return ResourceManager.GetString("UpdateAffiliate", resourceCulture);
            }
        }
        
        public static string IconHome {
            get {
                return ResourceManager.GetString("IconHome", resourceCulture);
            }
        }
        
        public static string SendActivationEmail {
            get {
                return ResourceManager.GetString("SendActivationEmail", resourceCulture);
            }
        }
        
        public static string DecimalSeparator {
            get {
                return ResourceManager.GetString("DecimalSeparator", resourceCulture);
            }
        }
        
        public static string MaxLengthEmail {
            get {
                return ResourceManager.GetString("MaxLengthEmail", resourceCulture);
            }
        }
        
        public static string MaxLengthCellPhone {
            get {
                return ResourceManager.GetString("MaxLengthCellPhone", resourceCulture);
            }
        }
        
        public static string MaxLengthDocument {
            get {
                return ResourceManager.GetString("MaxLengthDocument", resourceCulture);
            }
        }
        
        public static string MaxLengthName {
            get {
                return ResourceManager.GetString("MaxLengthName", resourceCulture);
            }
        }
        
        public static string IconNavigationBar {
            get {
                return ResourceManager.GetString("IconNavigationBar", resourceCulture);
            }
        }
        
        public static string GetDocumentTypesRegister {
            get {
                return ResourceManager.GetString("GetDocumentTypesRegister", resourceCulture);
            }
        }
        
        public static string CancelPreRegister {
            get {
                return ResourceManager.GetString("CancelPreRegister", resourceCulture);
            }
        }
        
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        public static string IconMyHealth {
            get {
                return ResourceManager.GetString("IconMyHealth", resourceCulture);
            }
        }
        
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        public static string ContentsController {
            get {
                return ResourceManager.GetString("ContentsController", resourceCulture);
            }
        }
        
        public static string GetLegalContent {
            get {
                return ResourceManager.GetString("GetLegalContent", resourceCulture);
            }
        }
        
        public static string TagPPC {
            get {
                return ResourceManager.GetString("TagPPC", resourceCulture);
            }
        }
        
        public static string TagTYCC {
            get {
                return ResourceManager.GetString("TagTYCC", resourceCulture);
            }
        }
        
        public static string IconCustomService {
            get {
                return ResourceManager.GetString("IconCustomService", resourceCulture);
            }
        }
        
        public static string PatientCode {
            get {
                return ResourceManager.GetString("PatientCode", resourceCulture);
            }
        }
        
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        public static string Installments {
            get {
                return ResourceManager.GetString("Installments", resourceCulture);
            }
        }
        
        public static string PaymentMethodCode {
            get {
                return ResourceManager.GetString("PaymentMethodCode", resourceCulture);
            }
        }
        
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        public static string PaymentMethodName {
            get {
                return ResourceManager.GetString("PaymentMethodName", resourceCulture);
            }
        }
        
        public static string GetAllFaqs {
            get {
                return ResourceManager.GetString("GetAllFaqs", resourceCulture);
            }
        }
        
        public static string GetContactPhones {
            get {
                return ResourceManager.GetString("GetContactPhones", resourceCulture);
            }
        }
        
        public static string IconCustomerService {
            get {
                return ResourceManager.GetString("IconCustomerService", resourceCulture);
            }
        }
        
        public static string IconLogOut {
            get {
                return ResourceManager.GetString("IconLogOut", resourceCulture);
            }
        }
        
        public static string SendServiceFile {
            get {
                return ResourceManager.GetString("SendServiceFile", resourceCulture);
            }
        }
        
        public static string ServicesController {
            get {
                return ResourceManager.GetString("ServicesController", resourceCulture);
            }
        }
        
        public static string GetServiceFile {
            get {
                return ResourceManager.GetString("GetServiceFile", resourceCulture);
            }
        }
        
        public static string GetServicesHistory {
            get {
                return ResourceManager.GetString("GetServicesHistory", resourceCulture);
            }
        }
        
        public static string GetServicesHistoryLists {
            get {
                return ResourceManager.GetString("GetServicesHistoryLists", resourceCulture);
            }
        }
        
        public static string TitleFileServiceHistory {
            get {
                return ResourceManager.GetString("TitleFileServiceHistory", resourceCulture);
            }
        }
        
        public static string AndroidProjectId {
            get {
                return ResourceManager.GetString("AndroidProjectId", resourceCulture);
            }
        }
        
        public static string NotificationHubName {
            get {
                return ResourceManager.GetString("NotificationHubName", resourceCulture);
            }
        }
        
        public static string NotificationHubConnectionString {
            get {
                return ResourceManager.GetString("NotificationHubConnectionString", resourceCulture);
            }
        }
        
        public static string AndroidProjectNumber {
            get {
                return ResourceManager.GetString("AndroidProjectNumber", resourceCulture);
            }
        }
        
        public static string HtmlChat {
            get {
                return ResourceManager.GetString("HtmlChat", resourceCulture);
            }
        }
        
        public static string EmergencyLine {
            get {
                return ResourceManager.GetString("EmergencyLine", resourceCulture);
            }
        }
        
        public static string GetSheduledServices {
            get {
                return ResourceManager.GetString("GetSheduledServices", resourceCulture);
            }
        }
        
        public static string CancelService {
            get {
                return ResourceManager.GetString("CancelService", resourceCulture);
            }
        }
        
        public static string HtmlChat2 {
            get {
                return ResourceManager.GetString("HtmlChat2", resourceCulture);
            }
        }
        
        public static string HtmlChat3 {
            get {
                return ResourceManager.GetString("HtmlChat3", resourceCulture);
            }
        }
        
        public static string PatientName {
            get {
                return ResourceManager.GetString("PatientName", resourceCulture);
            }
        }
        
        public static string MaxLengthBis {
            get {
                return ResourceManager.GetString("MaxLengthBis", resourceCulture);
            }
        }
        
        public static string AppliantDocument {
            get {
                return ResourceManager.GetString("AppliantDocument", resourceCulture);
            }
        }
        
        public static string AppliantDocumentType {
            get {
                return ResourceManager.GetString("AppliantDocumentType", resourceCulture);
            }
        }
        
        public static string CancelCoordinationRequest {
            get {
                return ResourceManager.GetString("CancelCoordinationRequest", resourceCulture);
            }
        }
        
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        public static string DoctorName {
            get {
                return ResourceManager.GetString("DoctorName", resourceCulture);
            }
        }
        
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        public static string InitDate {
            get {
                return ResourceManager.GetString("InitDate", resourceCulture);
            }
        }
        
        public static string PatientDocument {
            get {
                return ResourceManager.GetString("PatientDocument", resourceCulture);
            }
        }
        
        public static string PatientDocumentType {
            get {
                return ResourceManager.GetString("PatientDocumentType", resourceCulture);
            }
        }
        
        public static string Speciality {
            get {
                return ResourceManager.GetString("Speciality", resourceCulture);
            }
        }
        
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        public static string GetLocationInformationService {
            get {
                return ResourceManager.GetString("GetLocationInformationService", resourceCulture);
            }
        }
        
        public static string CoverageCode {
            get {
                return ResourceManager.GetString("CoverageCode", resourceCulture);
            }
        }
        
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        public static string AddMember {
            get {
                return ResourceManager.GetString("AddMember", resourceCulture);
            }
        }
        
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        public static string AddressDetails {
            get {
                return ResourceManager.GetString("AddressDetails", resourceCulture);
            }
        }
        
        public static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        public static string ApplicantCellPhone {
            get {
                return ResourceManager.GetString("ApplicantCellPhone", resourceCulture);
            }
        }
        
        public static string ApplicantHomePhone {
            get {
                return ResourceManager.GetString("ApplicantHomePhone", resourceCulture);
            }
        }
        
        public static string Bis {
            get {
                return ResourceManager.GetString("Bis", resourceCulture);
            }
        }
        
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        public static string Corner {
            get {
                return ResourceManager.GetString("Corner", resourceCulture);
            }
        }
        
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        public static string DoorNumber {
            get {
                return ResourceManager.GetString("DoorNumber", resourceCulture);
            }
        }
        
        public static string Neighborhood {
            get {
                return ResourceManager.GetString("Neighborhood", resourceCulture);
            }
        }
        
        public static string PatientCellPhone {
            get {
                return ResourceManager.GetString("PatientCellPhone", resourceCulture);
            }
        }
        
        public static string PatientHomePhone {
            get {
                return ResourceManager.GetString("PatientHomePhone", resourceCulture);
            }
        }
        
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        public static string HomeHealthCare {
            get {
                return ResourceManager.GetString("HomeHealthCare", resourceCulture);
            }
        }
        
        public static string MedicalOrientation {
            get {
                return ResourceManager.GetString("MedicalOrientation", resourceCulture);
            }
        }
        
        public static string ConfigurationChat {
            get {
                return ResourceManager.GetString("ConfigurationChat", resourceCulture);
            }
        }
        
        public static string CodeProfile {
            get {
                return ResourceManager.GetString("CodeProfile", resourceCulture);
            }
        }
        
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        public static string UrlPayCoordinationApp {
            get {
                return ResourceManager.GetString("UrlPayCoordinationApp", resourceCulture);
            }
        }
        
        public static string ServiceChatAgent {
            get {
                return ResourceManager.GetString("ServiceChatAgent", resourceCulture);
            }
        }
        
        public static string GetExistsMedicalHomeService {
            get {
                return ResourceManager.GetString("GetExistsMedicalHomeService", resourceCulture);
            }
        }
        
        public static string GetCancelMedicalHomeService {
            get {
                return ResourceManager.GetString("GetCancelMedicalHomeService", resourceCulture);
            }
        }
        
        public static string GetListStatusInvoice {
            get {
                return ResourceManager.GetString("GetListStatusInvoice", resourceCulture);
            }
        }
        
        public static string InvoicesController {
            get {
                return ResourceManager.GetString("InvoicesController", resourceCulture);
            }
        }
        
        public static string GetListInvoices {
            get {
                return ResourceManager.GetString("GetListInvoices", resourceCulture);
            }
        }
        
        public static string GetDetailInvoice {
            get {
                return ResourceManager.GetString("GetDetailInvoice", resourceCulture);
            }
        }
        
        public static string ValidateIsYoung {
            get {
                return ResourceManager.GetString("ValidateIsYoung", resourceCulture);
            }
        }
        
        public static string UrlPaymentMethodsApp {
            get {
                return ResourceManager.GetString("UrlPaymentMethodsApp", resourceCulture);
            }
        }
        
        public static string IosGoogleMapsAPIKey {
            get {
                return ResourceManager.GetString("IosGoogleMapsAPIKey", resourceCulture);
            }
        }
        
        public static string GetOpenTokDataForAffiliate {
            get {
                return ResourceManager.GetString("GetOpenTokDataForAffiliate", resourceCulture);
            }
        }
        
        public static string GetOpenTokRoutedSession {
            get {
                return ResourceManager.GetString("GetOpenTokRoutedSession", resourceCulture);
            }
        }
        
        public static string VideoCallController {
            get {
                return ResourceManager.GetString("VideoCallController", resourceCulture);
            }
        }
        
        public static string PostCallRating {
            get {
                return ResourceManager.GetString("PostCallRating", resourceCulture);
            }
        }
        
        public static string AccountController {
            get {
                return ResourceManager.GetString("AccountController", resourceCulture);
            }
        }
        
        public static string DeactivationType {
            get {
                return ResourceManager.GetString("DeactivationType", resourceCulture);
            }
        }
        
        public static string DeactivateUserAccount {
            get {
                return ResourceManager.GetString("DeactivateUserAccount", resourceCulture);
            }
        }
        
        public static string GetAsociatedUserAccounts {
            get {
                return ResourceManager.GetString("GetAsociatedUserAccounts", resourceCulture);
            }
        }
        
        public static string VerifyCodeForgortPassword {
            get {
                return ResourceManager.GetString("VerifyCodeForgortPassword", resourceCulture);
            }
        }
        
        public static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        public static string AuthorizeChangePasswordByCellPhone {
            get {
                return ResourceManager.GetString("AuthorizeChangePasswordByCellPhone", resourceCulture);
            }
        }
        
        public static string QueryVersionApp {
            get {
                return ResourceManager.GetString("QueryVersionApp", resourceCulture);
            }
        }
        
        public static string GetFirebaseConfiguration {
            get {
                return ResourceManager.GetString("GetFirebaseConfiguration", resourceCulture);
            }
        }
        
        public static string PostPatientServiceType {
            get {
                return ResourceManager.GetString("PostPatientServiceType", resourceCulture);
            }
        }
        
        public static string GetReasonsAbandonment {
            get {
                return ResourceManager.GetString("GetReasonsAbandonment", resourceCulture);
            }
        }
        
        public static string PostIntent {
            get {
                return ResourceManager.GetString("PostIntent", resourceCulture);
            }
        }
    }
}
