//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emi.Portal.Movil.Logic.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Emi.Portal.Movil.Logic.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        public static string AcceptTermsConditions {
            get {
                return ResourceManager.GetString("AcceptTermsConditions", resourceCulture);
            }
        }
        
        public static string ConfirmationRegister {
            get {
                return ResourceManager.GetString("ConfirmationRegister", resourceCulture);
            }
        }
        
        public static string DifferentEmail {
            get {
                return ResourceManager.GetString("DifferentEmail", resourceCulture);
            }
        }
        
        public static string DifferentPassword {
            get {
                return ResourceManager.GetString("DifferentPassword", resourceCulture);
            }
        }
        
        public static string DuplicateData {
            get {
                return ResourceManager.GetString("DuplicateData", resourceCulture);
            }
        }
        
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        public static string InvalidDInvalidNumber {
            get {
                return ResourceManager.GetString("InvalidDInvalidNumber", resourceCulture);
            }
        }
        
        public static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        public static string LoginAccount {
            get {
                return ResourceManager.GetString("LoginAccount", resourceCulture);
            }
        }
        
        public static string MailRequired {
            get {
                return ResourceManager.GetString("MailRequired", resourceCulture);
            }
        }
        
        public static string TitleNearbyClinics {
            get {
                return ResourceManager.GetString("TitleNearbyClinics", resourceCulture);
            }
        }
        
        public static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        public static string RecoverPassword {
            get {
                return ResourceManager.GetString("RecoverPassword", resourceCulture);
            }
        }
        
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        public static string SuccessfulCancellation {
            get {
                return ResourceManager.GetString("SuccessfulCancellation", resourceCulture);
            }
        }
        
        public static string TittleConfirmationRegister {
            get {
                return ResourceManager.GetString("TittleConfirmationRegister", resourceCulture);
            }
        }
        
        public static string TittleDuplicateData {
            get {
                return ResourceManager.GetString("TittleDuplicateData", resourceCulture);
            }
        }
        
        public static string TittleRecoverPassword {
            get {
                return ResourceManager.GetString("TittleRecoverPassword", resourceCulture);
            }
        }
        
        public static string TitlePQRS {
            get {
                return ResourceManager.GetString("TitlePQRS", resourceCulture);
            }
        }
        
        public static string TittleInSuccessfulCancellation {
            get {
                return ResourceManager.GetString("TittleInSuccessfulCancellation", resourceCulture);
            }
        }
        
        public static string TittleInvalidCode {
            get {
                return ResourceManager.GetString("TittleInvalidCode", resourceCulture);
            }
        }
        
        public static string TittleInvalidData {
            get {
                return ResourceManager.GetString("TittleInvalidData", resourceCulture);
            }
        }
        
        public static string TittleInvalidNumber {
            get {
                return ResourceManager.GetString("TittleInvalidNumber", resourceCulture);
            }
        }
        
        public static string TittleValidCode {
            get {
                return ResourceManager.GetString("TittleValidCode", resourceCulture);
            }
        }
        
        public static string TitleWithoutConnection {
            get {
                return ResourceManager.GetString("TitleWithoutConnection", resourceCulture);
            }
        }
        
        public static string ViewContactData {
            get {
                return ResourceManager.GetString("ViewContactData", resourceCulture);
            }
        }
        
        public static string WithoutConnection {
            get {
                return ResourceManager.GetString("WithoutConnection", resourceCulture);
            }
        }
        
        public static string WriteValidEmail {
            get {
                return ResourceManager.GetString("WriteValidEmail", resourceCulture);
            }
        }
        
        public static string TitleCard {
            get {
                return ResourceManager.GetString("TitleCard", resourceCulture);
            }
        }
        
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        public static string ExitApplicationMessage {
            get {
                return ResourceManager.GetString("ExitApplicationMessage", resourceCulture);
            }
        }
        
        public static string NoButtonText {
            get {
                return ResourceManager.GetString("NoButtonText", resourceCulture);
            }
        }
        
        public static string YesButtonText {
            get {
                return ResourceManager.GetString("YesButtonText", resourceCulture);
            }
        }
        
        public static string TittleInvalidEmail {
            get {
                return ResourceManager.GetString("TittleInvalidEmail", resourceCulture);
            }
        }
        
        public static string TittleErrorRegister {
            get {
                return ResourceManager.GetString("TittleErrorRegister", resourceCulture);
            }
        }
        
        public static string TittleInformationRegister {
            get {
                return ResourceManager.GetString("TittleInformationRegister", resourceCulture);
            }
        }
        
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        public static string CellPhoneRequired {
            get {
                return ResourceManager.GetString("CellPhoneRequired", resourceCulture);
            }
        }
        
        public static string TittleInformationNewCoordinatioFailed {
            get {
                return ResourceManager.GetString("TittleInformationNewCoordinatioFailed", resourceCulture);
            }
        }
        
        public static string TittleNewCoordination {
            get {
                return ResourceManager.GetString("TittleNewCoordination", resourceCulture);
            }
        }
        
        public static string CancelCoordination {
            get {
                return ResourceManager.GetString("CancelCoordination", resourceCulture);
            }
        }
        
        public static string CancelCoordinationTittle {
            get {
                return ResourceManager.GetString("CancelCoordinationTittle", resourceCulture);
            }
        }
        
        public static string TittleMedicalCenterCoordination {
            get {
                return ResourceManager.GetString("TittleMedicalCenterCoordination", resourceCulture);
            }
        }
        
        public static string TitlePersonalInformation {
            get {
                return ResourceManager.GetString("TitlePersonalInformation", resourceCulture);
            }
        }
        
        public static string TitleCertificates {
            get {
                return ResourceManager.GetString("TitleCertificates", resourceCulture);
            }
        }
        
        public static string TitleMyAccount {
            get {
                return ResourceManager.GetString("TitleMyAccount", resourceCulture);
            }
        }
        
        public static string TitleBenericiaries {
            get {
                return ResourceManager.GetString("TitleBenericiaries", resourceCulture);
            }
        }
        
        public static string TitleFamily {
            get {
                return ResourceManager.GetString("TitleFamily", resourceCulture);
            }
        }
        
        public static string ActivePerson {
            get {
                return ResourceManager.GetString("ActivePerson", resourceCulture);
            }
        }
        
        public static string PQRSText {
            get {
                return ResourceManager.GetString("PQRSText", resourceCulture);
            }
        }
        
        public static string InactivePerson {
            get {
                return ResourceManager.GetString("InactivePerson", resourceCulture);
            }
        }
        
        public static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        public static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        public static string EstimatedTime {
            get {
                return ResourceManager.GetString("EstimatedTime", resourceCulture);
            }
        }
        
        public static string EstimatedTimeZone {
            get {
                return ResourceManager.GetString("EstimatedTimeZone", resourceCulture);
            }
        }
        
        public static string TitleQuestion {
            get {
                return ResourceManager.GetString("TitleQuestion", resourceCulture);
            }
        }
        
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        public static string DeleteFamilyMemberMessage {
            get {
                return ResourceManager.GetString("DeleteFamilyMemberMessage", resourceCulture);
            }
        }
        
        public static string DeleteFamilyMemberTitle {
            get {
                return ResourceManager.GetString("DeleteFamilyMemberTitle", resourceCulture);
            }
        }
        
        public static string EditFamilyTitle {
            get {
                return ResourceManager.GetString("EditFamilyTitle", resourceCulture);
            }
        }
        
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        public static string DocumentRequired {
            get {
                return ResourceManager.GetString("DocumentRequired", resourceCulture);
            }
        }
        
        public static string DocumentTypeRequired {
            get {
                return ResourceManager.GetString("DocumentTypeRequired", resourceCulture);
            }
        }
        
        public static string SunamesRequired {
            get {
                return ResourceManager.GetString("SunamesRequired", resourceCulture);
            }
        }
        
        public static string TitleMyBeneficiaries {
            get {
                return ResourceManager.GetString("TitleMyBeneficiaries", resourceCulture);
            }
        }
        
        public static string TitleChangePassword {
            get {
                return ResourceManager.GetString("TitleChangePassword", resourceCulture);
            }
        }
        
        public static string TitlePersonalData {
            get {
                return ResourceManager.GetString("TitlePersonalData", resourceCulture);
            }
        }
        
        public static string TitleChangeEmail {
            get {
                return ResourceManager.GetString("TitleChangeEmail", resourceCulture);
            }
        }
        
        public static string TitleDisableAccount {
            get {
                return ResourceManager.GetString("TitleDisableAccount", resourceCulture);
            }
        }
        
        public static string AllFieldsRequired {
            get {
                return ResourceManager.GetString("AllFieldsRequired", resourceCulture);
            }
        }
        
        public static string AllFieldStarRequired {
            get {
                return ResourceManager.GetString("AllFieldStarRequired", resourceCulture);
            }
        }
        
        public static string MessagePersonalDataPage {
            get {
                return ResourceManager.GetString("MessagePersonalDataPage", resourceCulture);
            }
        }
        
        public static string TitleLandingPage {
            get {
                return ResourceManager.GetString("TitleLandingPage", resourceCulture);
            }
        }
        
        public static string SendActivationEmail {
            get {
                return ResourceManager.GetString("SendActivationEmail", resourceCulture);
            }
        }
        
        public static string PasswordDescription {
            get {
                return ResourceManager.GetString("PasswordDescription", resourceCulture);
            }
        }
        
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        public static string CellConditions {
            get {
                return ResourceManager.GetString("CellConditions", resourceCulture);
            }
        }
        
        public static string CellPhoneConditions {
            get {
                return ResourceManager.GetString("CellPhoneConditions", resourceCulture);
            }
        }
        
        public static string TitleEmpty {
            get {
                return ResourceManager.GetString("TitleEmpty", resourceCulture);
            }
        }
        
        public static string TitleConfirmedCoordination {
            get {
                return ResourceManager.GetString("TitleConfirmedCoordination", resourceCulture);
            }
        }
        
        public static string TitleNoConfirmedCoordination {
            get {
                return ResourceManager.GetString("TitleNoConfirmedCoordination", resourceCulture);
            }
        }
        
        public static string TitleExpiredMedicalServices {
            get {
                return ResourceManager.GetString("TitleExpiredMedicalServices", resourceCulture);
            }
        }
        
        public static string ViewMedicalCenterList {
            get {
                return ResourceManager.GetString("ViewMedicalCenterList", resourceCulture);
            }
        }
        
        public static string TitleEditFamily {
            get {
                return ResourceManager.GetString("TitleEditFamily", resourceCulture);
            }
        }
        
        public static string EmailCondition {
            get {
                return ResourceManager.GetString("EmailCondition", resourceCulture);
            }
        }
        
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        public static string DontEditFamilyMember {
            get {
                return ResourceManager.GetString("DontEditFamilyMember", resourceCulture);
            }
        }
        
        public static string TitleMyHealth {
            get {
                return ResourceManager.GetString("TitleMyHealth", resourceCulture);
            }
        }
        
        public static string TitleServicesHistory {
            get {
                return ResourceManager.GetString("TitleServicesHistory", resourceCulture);
            }
        }
        
        public static string TitleCustomService {
            get {
                return ResourceManager.GetString("TitleCustomService", resourceCulture);
            }
        }
        
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        public static string DataManagementPolicy {
            get {
                return ResourceManager.GetString("DataManagementPolicy", resourceCulture);
            }
        }
        
        public static string TitleCustomerServices {
            get {
                return ResourceManager.GetString("TitleCustomerServices", resourceCulture);
            }
        }
        
        public static string TitleMedicalCare {
            get {
                return ResourceManager.GetString("TitleMedicalCare", resourceCulture);
            }
        }
        
        public static string TitleTelephoneLinesAvailable {
            get {
                return ResourceManager.GetString("TitleTelephoneLinesAvailable", resourceCulture);
            }
        }
        
        public static string TitleConfirmNewCoordination {
            get {
                return ResourceManager.GetString("TitleConfirmNewCoordination", resourceCulture);
            }
        }
        
        public static string TitlePay {
            get {
                return ResourceManager.GetString("TitlePay", resourceCulture);
            }
        }
        
        public static string TitlePayCoordination {
            get {
                return ResourceManager.GetString("TitlePayCoordination", resourceCulture);
            }
        }
        
        public static string TitleFaqs {
            get {
                return ResourceManager.GetString("TitleFaqs", resourceCulture);
            }
        }
        
        public static string TitleLogOut {
            get {
                return ResourceManager.GetString("TitleLogOut", resourceCulture);
            }
        }
        
        public static string CancelSheduledService {
            get {
                return ResourceManager.GetString("CancelSheduledService", resourceCulture);
            }
        }
        
        public static string ChatCustomerService {
            get {
                return ResourceManager.GetString("ChatCustomerService", resourceCulture);
            }
        }
        
        public static string TitleSheduledServices {
            get {
                return ResourceManager.GetString("TitleSheduledServices", resourceCulture);
            }
        }
        
        public static string TitleCalificateServices {
            get {
                return ResourceManager.GetString("TitleCalificateServices", resourceCulture);
            }
        }
        
        public static string EmailDescription {
            get {
                return ResourceManager.GetString("EmailDescription", resourceCulture);
            }
        }
        
        public static string TitleRequestRervice {
            get {
                return ResourceManager.GetString("TitleRequestRervice", resourceCulture);
            }
        }
        
        public static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        public static string DepartmentRequired {
            get {
                return ResourceManager.GetString("DepartmentRequired", resourceCulture);
            }
        }
        
        public static string DirectionRequired {
            get {
                return ResourceManager.GetString("DirectionRequired", resourceCulture);
            }
        }
        
        public static string StreetRequired {
            get {
                return ResourceManager.GetString("StreetRequired", resourceCulture);
            }
        }
        
        public static string NeighborhoodRequired {
            get {
                return ResourceManager.GetString("NeighborhoodRequired", resourceCulture);
            }
        }
        
        public static string ErrorDoorNumber {
            get {
                return ResourceManager.GetString("ErrorDoorNumber", resourceCulture);
            }
        }
        
        public static string TitleProductsAndPlans {
            get {
                return ResourceManager.GetString("TitleProductsAndPlans", resourceCulture);
            }
        }
        
        public static string ErrorMainRoadType {
            get {
                return ResourceManager.GetString("ErrorMainRoadType", resourceCulture);
            }
        }
        
        public static string ErrorNumberMainRoad {
            get {
                return ResourceManager.GetString("ErrorNumberMainRoad", resourceCulture);
            }
        }
        
        public static string ErrorNumberNomenclature {
            get {
                return ResourceManager.GetString("ErrorNumberNomenclature", resourceCulture);
            }
        }
        
        public static string CompleteData {
            get {
                return ResourceManager.GetString("CompleteData", resourceCulture);
            }
        }
        
        public static string AddressOutsideTheCoverageArea {
            get {
                return ResourceManager.GetString("AddressOutsideTheCoverageArea", resourceCulture);
            }
        }
        
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        public static string CancelChat {
            get {
                return ResourceManager.GetString("CancelChat", resourceCulture);
            }
        }
        
        public static string ExitChat {
            get {
                return ResourceManager.GetString("ExitChat", resourceCulture);
            }
        }
        
        public static string AddFamiliyServicePage {
            get {
                return ResourceManager.GetString("AddFamiliyServicePage", resourceCulture);
            }
        }
        
        public static string CoverageMessage {
            get {
                return ResourceManager.GetString("CoverageMessage", resourceCulture);
            }
        }
        
        public static string AddFamiliyCoordinationPage {
            get {
                return ResourceManager.GetString("AddFamiliyCoordinationPage", resourceCulture);
            }
        }
        
        public static string FamilyDoesNotFind {
            get {
                return ResourceManager.GetString("FamilyDoesNotFind", resourceCulture);
            }
        }
        
        public static string HomeCareDescription {
            get {
                return ResourceManager.GetString("HomeCareDescription", resourceCulture);
            }
        }
        
        public static string MedicalOrientationDescription {
            get {
                return ResourceManager.GetString("MedicalOrientationDescription", resourceCulture);
            }
        }
        
        public static string TitleProgressMedicalHomeService {
            get {
                return ResourceManager.GetString("TitleProgressMedicalHomeService", resourceCulture);
            }
        }
        
        public static string CancelMedicalHomeService {
            get {
                return ResourceManager.GetString("CancelMedicalHomeService", resourceCulture);
            }
        }
        
        public static string MessageCancelMedigalHomeService {
            get {
                return ResourceManager.GetString("MessageCancelMedigalHomeService", resourceCulture);
            }
        }
        
        public static string MessageProgressMedicalHomeService {
            get {
                return ResourceManager.GetString("MessageProgressMedicalHomeService", resourceCulture);
            }
        }
        
        public static string TitleMyInvoices {
            get {
                return ResourceManager.GetString("TitleMyInvoices", resourceCulture);
            }
        }
        
        public static string MessageValidateDates {
            get {
                return ResourceManager.GetString("MessageValidateDates", resourceCulture);
            }
        }
        
        public static string TitleValidateDates {
            get {
                return ResourceManager.GetString("TitleValidateDates", resourceCulture);
            }
        }
        
        public static string TitleInvoiceDetail {
            get {
                return ResourceManager.GetString("TitleInvoiceDetail", resourceCulture);
            }
        }
        
        public static string TitleMyServices {
            get {
                return ResourceManager.GetString("TitleMyServices", resourceCulture);
            }
        }
        
        public static string CallWarningMessage {
            get {
                return ResourceManager.GetString("CallWarningMessage", resourceCulture);
            }
        }
        
        public static string TitleMessageWaitCall {
            get {
                return ResourceManager.GetString("TitleMessageWaitCall", resourceCulture);
            }
        }
        
        public static string Lostcall {
            get {
                return ResourceManager.GetString("Lostcall", resourceCulture);
            }
        }
        
        public static string MessageWaitCall {
            get {
                return ResourceManager.GetString("MessageWaitCall", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string PickDocument {
            get {
                return ResourceManager.GetString("PickDocument", resourceCulture);
            }
        }
        
        public static string SelectedPhotoGalery {
            get {
                return ResourceManager.GetString("SelectedPhotoGalery", resourceCulture);
            }
        }
        
        public static string MessageWelcomeVideoCall {
            get {
                return ResourceManager.GetString("MessageWelcomeVideoCall", resourceCulture);
            }
        }
        
        public static string WaitPlease {
            get {
                return ResourceManager.GetString("WaitPlease", resourceCulture);
            }
        }
        
        public static string ValidateVideoChat {
            get {
                return ResourceManager.GetString("ValidateVideoChat", resourceCulture);
            }
        }
        
        public static string ValidatePermissions {
            get {
                return ResourceManager.GetString("ValidatePermissions", resourceCulture);
            }
        }
        
        public static string TestServiceOpenTok {
            get {
                return ResourceManager.GetString("TestServiceOpenTok", resourceCulture);
            }
        }
        
        public static string VideoCallTitle {
            get {
                return ResourceManager.GetString("VideoCallTitle", resourceCulture);
            }
        }
        
        public static string EvaluateVideoCallTittle {
            get {
                return ResourceManager.GetString("EvaluateVideoCallTittle", resourceCulture);
            }
        }
        
        public static string QuestionEvaluate {
            get {
                return ResourceManager.GetString("QuestionEvaluate", resourceCulture);
            }
        }
        
        public static string ObservationEvaluate {
            get {
                return ResourceManager.GetString("ObservationEvaluate", resourceCulture);
            }
        }
        
        public static string NotNowEvaluate {
            get {
                return ResourceManager.GetString("NotNowEvaluate", resourceCulture);
            }
        }
        
        public static string SendEvaluate {
            get {
                return ResourceManager.GetString("SendEvaluate", resourceCulture);
            }
        }
        
        public static string TextChangeEmail {
            get {
                return ResourceManager.GetString("TextChangeEmail", resourceCulture);
            }
        }
        
        public static string EmailEqualError {
            get {
                return ResourceManager.GetString("EmailEqualError", resourceCulture);
            }
        }
        
        public static string EmailCurrentError {
            get {
                return ResourceManager.GetString("EmailCurrentError", resourceCulture);
            }
        }
        
        public static string ConfirmChangeEmail {
            get {
                return ResourceManager.GetString("ConfirmChangeEmail", resourceCulture);
            }
        }
        
        public static string QuestionConfirmChangeEmail {
            get {
                return ResourceManager.GetString("QuestionConfirmChangeEmail", resourceCulture);
            }
        }
        
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        public static string EmailOrPhoneRequired {
            get {
                return ResourceManager.GetString("EmailOrPhoneRequired", resourceCulture);
            }
        }
        
        public static string PhoneValidate {
            get {
                return ResourceManager.GetString("PhoneValidate", resourceCulture);
            }
        }
        
        public static string VerifyCodeRequired {
            get {
                return ResourceManager.GetString("VerifyCodeRequired", resourceCulture);
            }
        }
        
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        public static string UpdateRequired {
            get {
                return ResourceManager.GetString("UpdateRequired", resourceCulture);
            }
        }
        
        public static string NextAtetion {
            get {
                return ResourceManager.GetString("NextAtetion", resourceCulture);
            }
        }
        
        public static string NumberAtetion {
            get {
                return ResourceManager.GetString("NumberAtetion", resourceCulture);
            }
        }
        
        public static string TitleDoctorNotAvailable {
            get {
                return ResourceManager.GetString("TitleDoctorNotAvailable", resourceCulture);
            }
        }
        
        public static string DoctorNotAvailable {
            get {
                return ResourceManager.GetString("DoctorNotAvailable", resourceCulture);
            }
        }
        
        public static string SelectStar {
            get {
                return ResourceManager.GetString("SelectStar", resourceCulture);
            }
        }
    }
}
